# create a data source to select the latest AMI generated by the packer images

data "aws_ami" "elasticsearch_ami" {
  most_recent = true
  owners      = ["self"]
  name_regex  = "^pelias-elasticsearch-\\d{3}"
}
