apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      # filebeat has to run as root to read logs, since the logs
      # on the host system are all owned by root. this is a little
      # scary, but at least all the host mounts are read-only, to minimize
      # possible damage.
      securityContext:
        runAsUser: 0
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:5.6.0
        # override the configuration path. because kubernetes can only mount directories
        # and not individual files
        command: [ "/usr/share/filebeat/filebeat"]
        args: [ "-e", "-path.config", "/usr/share/filebeat/config"]
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
        env:
          - name: LOGSTASH_HOSTS
            value: logstash-service:5044
          - name: LOG_LEVEL
            value: info
          - name: FILEBEAT_HOST
            valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/filebeat/config
        - name: varlog
          mountPath: /var/log/hostlogs
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: vartmp
          mountPath: /var/tmp/filebeat
      terminationGracePeriodSeconds: 30
      # allow filebeat to also be scheduled on master nodes, so we can pick up kubernetes logs
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      # mount the root of var log so that system level logs (like kube-apiserver and etcd) can be read
      - name: varlog
        hostPath:
          path: /var/log
      # mount /var/tmp as a persistent place to store the filebeat registry
      - name: vartmp
        hostPath:
          path: /var/tmp
      # mount /var/log/containers to get friendly named symlinks to actual logs
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      # mount /var/log/pods as its where pod logs are collected
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      # mount /var/lib/docker/containers which is where the logs _actually_ are
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # mount the configmap with the filebeat config file
      - name: config-volume
        configMap:
          name: logging-configmap
          items:
            - key: filebeat.yml
              path: filebeat.yml
